name: Scheduled FTP Upload

on:
  schedule:
    - cron: '0 17 * * *'  # 北京时间凌晨1点 (UTC 17:00)
  workflow_dispatch:

jobs:
  upload:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
        
    - name: Run FTP Upload
      env:
        FTP_HOST: cn-nb1.rains3.com
        FTP_PORT: 8021
        FTP_USER: oDvjrdGc8bSdN5sf
        FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}  # 确保与secret名称一致
      run: python ftp_upload.py
