name: FTP File Upload

on:
  schedule:
    - cron: '0 17 * * *'  # 北京时间凌晨1点 (UTC 17:00)
  workflow_dispatch:
    inputs:
      environment:
        description: '选择运行环境'
        required: true
        default: 'production'
        type: choice
        options:
        - production
        - test
      confirm:
        description: '确认执行上传 (输入YES继续)'
        required: true
        default: 'NO'
        type: string

jobs:
  upload:
    runs-on: ubuntu-latest
    
    # 添加手动运行的条件检查
    if: |
      github.event_name == 'schedule' ||
      (github.event_name == 'workflow_dispatch' && 
       inputs.confirm == 'YES')
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
        
    - name: Show manual run info
      if: github.event_name == 'workflow_dispatch'
      run: |
        echo "=== 手动运行参数 ==="
        echo "环境: ${{ github.event.inputs.environment }}"
        echo "确认: ${{ github.event.inputs.confirm }}"
        echo "==================="
        
    - name: Run FTP Upload
      env:
        FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
      run: python ftp_upload.py
      
    - name: Upload result notification
      if: always()
      run: |
        if [ $? -eq 0 ]; then
          echo "::notice::FTP上传成功完成!"
        else
          echo "::error::FTP上传失败!"
        fi
